Fix #533: OIDC: Configuration of mobile application
wultra/powerauth-restful-integration pull request #539
Opened 2024-08-05 09:41 UTC by banterCZ

2024-08-05 12:52 UTC, romanstrobl approved these changes
Looks OK.

2024-08-06 05:10 UTC, banterCZ commented on powerauth-restful-security-spring/src/main/java/io/getlime/security/powerauth/rest/api/spring/controller/ApplicationConfigurationController.java
> +    public OidcApplicationConfigurationResponse fetchOidcConfiguration(@EncryptedRequestBody OidcApplicationConfigurationRequest request, EncryptionContext encryptionContext) throws PowerAuthApplicat
@romanstrobl Don't we want to wrap it into `ObjectResponse`?

2024-08-06 06:02 UTC, petrdvorak requested changes
Nope, not in this repo...

2024-08-06 07:06 UTC, banterCZ commented on powerauth-restful-model/src/main/java/io/getlime/security/powerauth/rest/api/model/response/OidcApplicationConfigurationResponse.java
> +    private List<String> scopes;
Mind that in the TLDR there is
> a comma-separated array of scopes which must contain `openid`

2024-08-06 07:29 UTC, banterCZ commented
> Nope, not in this repo...

Ok, let's move it to the enrollment server.

2024-08-06 07:29 UTC, closed without merging